// <auto-generated />
namespace Election.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingnavigationpropertyintopoll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingnavigationpropertyintopoll));
        
        string IMigrationMetadata.Id
        {
            get { return "201701171612482_Adding-navigation-property-into-poll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
