// <auto-generated />
namespace Election.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changingpollprimarykeytoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changingpollprimarykeytoint));
        
        string IMigrationMetadata.Id
        {
            get { return "201701161936524_Changing-poll-primary-key-to-int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
