// <auto-generated />
namespace Election.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingnavigationpropertyintovote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingnavigationpropertyintovote));
        
        string IMigrationMetadata.Id
        {
            get { return "201701171302506_Adding-navigation-property-into-vote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
