// <auto-generated />
namespace Election.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removingsomerequiredvaluesfromvote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removingsomerequiredvaluesfromvote));
        
        string IMigrationMetadata.Id
        {
            get { return "201701171440210_Removing-some-required-values-from-vote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
