// <auto-generated />
namespace Election.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Merging2contextsinto1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Merging2contextsinto1));
        
        string IMigrationMetadata.Id
        {
            get { return "201701182228069_Merging-2-contexts-into-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
